### PR TITLE
Delete EdinaPublicationsAPIService

### PR DESCRIPTION
**Pull request by philboeselager**

### CODE REVIEW

**Review by hornmo — CHANGES_REQUESTED** [review]
The service class is still referenced in [TitleAugmentService](https://github.com/openlibraryenvironment/gokb/blob/g3_master/server/gokbg3/grails-app/services/org/gokb/TitleAugmentService.groovy), where `augment()` should be adjusted to current workflows.

**Comment by philboeselager** [comment]
> The service class is still referenced in [TitleAugmentService](https://github.com/openlibraryenvironment/gokb/blob/g3_master/server/gokbg3/grails-app/services/org/gokb/TitleAugmentService.groovy), where `augment()` should be adjusted to current workflows.

I'm sorry for that. How to adjust `augment()`? Maybe you know better how to do that, so that I can review?

**Comment by hornmo** [comment]
Sure, I'll just go from here and request a review when I'm done.

**Comment by philboeselager** [comment]
@hornmo You have not yet requested a review, have you?

**Review by VolkerHBZ — APPROVED** [review]

**Review by hornmo — APPROVED** [review]

**Pull request merged**
